### ISSUE TITLE
问一下开源吗，可以商用吗

### ISSUE THREAD

**Issue by Yukiri2887** [Yuexs/OrchardCoreExample#6]
rt

**Comment by Yukiri2887** [comment]
顺便问一下webapi和工作流怎么配合使用

**Comment by Yuexs** [comment]
完全开源的，示例有工作流的使用，和webapi使用没有区别

**Comment by Yukiri2887** [comment]
抱歉还是有点没懂这个webapi怎么调用，能加一下qq交流吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yuexs/OrchardCoreExample"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月11日(星期一) 中午12:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yuexs/OrchardCoreExample] 问一下开源吗，可以商用吗 (Issue #6)





 
完全开源的，示例有工作流的使用，和webapi使用没有区别

**Comment by Yukiri2887** [comment]
好的，谢谢，能加个QQ交流吗oc上有一些不太懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 中午12:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Yuexs/OrchardCoreExample] 问一下开源吗，可以商用吗 (Issue #6)





 
完全开源的，示例有工作流的使用，和webapi使用没有区别
